import type { Category, Recipe } from '../types/content';

export const demoCategories: Category[] = [
  {
    _id: 'cat-main',
    title: 'ארוחות עיקריות',
    slug: 'main-dishes',
    description: 'המנות שמרכזות את כולם סביב השולחן.',
    image: { localSrc: '/images/category-main-dishes.webp', alt: 'לזניה ביתית בתבנית אפייה' },
  },
  {
    _id: 'cat-baking',
    title: 'אפייה ולחמים',
    slug: 'baking',
    description: 'ריח של בית שיוצא מהתנור.',
    image: { localSrc: '/images/challah.webp', alt: 'חלות טריות' },
  },
  {
    _id: 'cat-salads',
    title: 'סלטים ותוספות',
    slug: 'salads',
    description: 'צבע, רעננות וכל מה שבצד.',
    image: { localSrc: '/images/salad.webp', alt: 'סלט ירקות טרי' },
  },
  {
    _id: 'cat-desserts',
    title: 'קינוחים',
    slug: 'desserts',
    description: 'משהו מתוק לסיים איתו.',
    image: { localSrc: '/images/cake.webp', alt: 'עוגת תפוזים ביתית' },
  },
];

export const demoRecipes: Recipe[] = [
  {
    _id: 'demo-chicken',
    title: 'עוף בתנור עם לימון ועשבי תיבול',
    slug: 'lemon-herb-roast-chicken',
    description:
      'מנה משפחתית נעימה של עוף זהוב, תפוחי אדמה ולימון. מכינים בתבנית אחת ונותנים לתנור לעשות את שלו.',
    image: { localSrc: '/images/hero-roast-chicken.webp', alt: 'עוף צלוי עם לימון ותפוחי אדמה' },
    category: demoCategories[0],
    prepMinutes: 20,
    cookMinutes: 90,
    restMinutes: 10,
    activeMinutes: 30,
    elapsedMinutes: 120,
    servings: 6,
    doneness: [{ level: 'מוכן ובטוח להגשה', finalMinC: 74, isSafetyTarget: true }],
    difficulty: 'easy',
    kashrutType: 'meat',
    featured: true,
    tags: ['שבת', 'ארוחה משפחתית'],
    publishedAt: '2026-09-20',
    demo: true,
    ingredientGroups: [
      {
        title: 'למנה',
        items: [
          { amount: '1', quantity: 1, name: 'עוף שלם', note: 'כ־1.5–2 ק״ג' },
          { amount: '6', quantity: 6, name: 'תפוחי אדמה קטנים, חצויים' },
          { amount: '2', quantity: 2, name: 'לימונים' },
          { amount: '4', quantity: 4, name: 'שיני שום' },
          { amount: '3', quantity: 3, unit: 'כפות', name: 'שמן זית' },
          { amount: '1', quantity: 1, unit: 'כפית', name: 'מלח' },
          { amount: '½', quantity: 0.5, unit: 'כפית', name: 'פלפל שחור' },
          { amount: '3', quantity: 3, name: 'ענפי תימין או רוזמרין' },
        ],
      },
    ],
    steps: [
      { text: 'מחממים תנור ל־200 מעלות. מסדרים בתבנית את העוף ותפוחי האדמה.' },
      {
        text: 'סוחטים לימון אחד על הכול. מוסיפים פרוסות מהלימון השני, שום, שמן זית, מלח, פלפל ועשבי תיבול. מערבבים היטב.',
      },
      {
        text: 'אופים כ־90 דקות, לפי גודל העוף, עד שהעוף זהוב ותפוחי האדמה רכים. מודדים את חום העוף בשלושה מקומות, בלי לגעת בעצם. הופכים את תפוחי האדמה באמצע האפייה.',
        temperatureC: 200,
        cue: 'העוף מגיע ל־74°C לפחות בחלק העמוק של החזה, הירך והכנף.',
      },
      { text: 'מניחים למנה לנוח 10 דקות ומגישים עם הנוזלים שבתבנית.' },
    ],
    tips: ['אם החלק העליון משחים מהר מדי, מכסים ברפיון בנייר אפייה וממשיכים לאפות.'],
  },
  {
    _id: 'demo-challah',
    title: 'חלה ביתית רכה לשישי',
    slug: 'soft-shabbat-challah',
    description: 'חלה רכה עם קרום זהוב. הכנה איטית ונעימה לקראת סוף השבוע.',
    image: { localSrc: '/images/challah.webp', alt: 'חלה קלועה אפויה' },
    category: demoCategories[1],
    prepMinutes: 30,
    cookMinutes: 30,
    restMinutes: 130,
    activeMinutes: 45,
    elapsedMinutes: 190,
    servings: 12,
    difficulty: 'medium',
    kashrutType: 'pareve',
    tags: ['שבת', 'אפייה'],
    publishedAt: '2026-09-19',
    demo: true,
    ingredientGroups: [
      {
        title: 'לשתי חלות',
        items: [
          { amount: '1', quantity: 1, unit: 'ק״ג', name: 'קמח לבן' },
          { amount: '2', quantity: 2, unit: 'כפות', name: 'שמרים יבשים' },
          { amount: '½', quantity: 0.5, unit: 'כוס', name: 'סוכר' },
          { amount: '2', quantity: 2, unit: 'כוסות', name: 'מים פושרים' },
          { amount: '½', quantity: 0.5, unit: 'כוס', name: 'שמן' },
          { amount: '1', quantity: 1, unit: 'כף', name: 'מלח' },
          { amount: '1', quantity: 1, name: 'ביצה להברשה' },
          { name: 'שומשום לפיזור' },
        ],
      },
    ],
    steps: [
      {
        text: 'מערבבים קמח, שמרים וסוכר. מוסיפים מים ושמן ולשים כמה דקות. מוסיפים מלח ולשים עד שנוצר בצק חלק וגמיש.',
      },
      { text: 'מכסים ומתפיחים כשעה וחצי, עד להכפלת הנפח.' },
      {
        text: 'מחלקים את הבצק לשתי חלות, קולעים ומניחים על תבנית עם נייר אפייה. מתפיחים עוד כ־40 דקות.',
      },
      { text: 'מברישים בביצה, מפזרים שומשום ואופים ב־180 מעלות כ־30 דקות עד להזהבה.' },
    ],
    tips: ['אפשר לקרר לגמרי ולהקפיא, עטוף היטב.'],
  },
  {
    _id: 'demo-salad',
    title: 'סלט קצוץ עם לימון ועשבי תיבול',
    slug: 'chopped-herb-salad',
    description: 'סלט רענן ומלא צבע שמתאים כמעט לכל ארוחה. קוצצים דק ומגישים מיד.',
    image: { localSrc: '/images/salad.webp', alt: 'סלט ירקות קצוץ' },
    category: demoCategories[2],
    prepMinutes: 15,
    cookMinutes: 0,
    activeMinutes: 15,
    elapsedMinutes: 15,
    servings: 4,
    difficulty: 'easy',
    kashrutType: 'pareve',
    dietaryLabels: ['vegetarian', 'glutenFree', 'lactoseFree'],
    tags: ['מהיר'],
    publishedAt: '2026-09-18',
    demo: true,
    ingredientGroups: [
      {
        items: [
          { amount: '4', quantity: 4, name: 'עגבניות' },
          { amount: '3', quantity: 3, name: 'מלפפונים' },
          { amount: '½', quantity: 0.5, name: 'בצל סגול' },
          { amount: '½', quantity: 0.5, unit: 'צרור', name: 'פטרוזיליה' },
          { amount: '1', quantity: 1, name: 'לימון' },
          { amount: '2', quantity: 2, unit: 'כפות', name: 'שמן זית' },
          { name: 'מלח ופלפל לפי הטעם' },
        ],
      },
    ],
    steps: [
      { text: 'קוצצים את העגבניות, המלפפונים והבצל לקוביות קטנות. קוצצים את הפטרוזיליה.' },
      { text: 'מערבבים בקערה עם מיץ לימון, שמן זית, מלח ופלפל. טועמים ומתקנים תיבול.' },
    ],
    tips: ['מוסיפים את התיבול סמוך להגשה כדי לשמור על הפריכות.'],
  },
  {
    _id: 'demo-cake',
    title: 'עוגת תפוזים בחושה',
    slug: 'simple-orange-cake',
    description: 'עוגה פשוטה, ריחנית ורכה ליד הקפה. בדיוק מה שצריך כשהבית מתמלא אורחים.',
    image: { localSrc: '/images/cake.webp', alt: 'עוגת תפוזים עם פרוסה חתוכה' },
    category: demoCategories[3],
    prepMinutes: 20,
    cookMinutes: 45,
    activeMinutes: 20,
    elapsedMinutes: 65,
    servings: 10,
    difficulty: 'easy',
    kashrutType: 'pareve',
    dietaryLabels: ['lactoseFree'],
    tags: ['אפייה', 'אירוח'],
    publishedAt: '2026-09-17',
    demo: true,
    ingredientGroups: [
      {
        items: [
          { amount: '3', quantity: 3, name: 'ביצים' },
          { amount: '¾', quantity: 0.75, unit: 'כוס', name: 'סוכר' },
          { amount: '½', quantity: 0.5, unit: 'כוס', name: 'שמן' },
          { amount: '1', quantity: 1, unit: 'כוס', name: 'מיץ תפוזים סחוט' },
          { amount: '2', quantity: 2, unit: 'כוסות', name: 'קמח' },
          { amount: '2', quantity: 2, unit: 'כפיות', name: 'אבקת אפייה' },
          { amount: '1', quantity: 1, unit: 'כפית', name: 'גרידת תפוז' },
        ],
      },
    ],
    steps: [
      { text: 'מחממים תנור ל־170 מעלות ומשמנים תבנית עגולה בקוטר 24 ס״מ.' },
      { text: 'טורפים ביצים וסוכר. מוסיפים שמן, מיץ תפוזים וגרידה ומערבבים.' },
      { text: 'מוסיפים קמח ואבקת אפייה ומערבבים רק עד שהבלילה אחידה.' },
      { text: 'יוצקים לתבנית ואופים כ־45 דקות, עד שקיסם יוצא נקי. מצננים לפני החיתוך.' },
    ],
    tips: ['אפשר לפזר מעט אבקת סוכר אחרי שהעוגה מתקררת.'],
  },
];
